#!/bin/env sh

# On running the script, append additional options and arguments if needed
output/host/bin/qemu-system-aarch64 -M virt -cpu cortex-a53 -nographic -smp 1 -kernel output/images/Image \
"$@"

# Opts and args that might be useful (check out BR/board/qemu for reference):
# -append "rootwait root=/dev/vda console=ttyAMA0" \
# -netdev user,id=eth0 \
# -device virtio-net-device,netdev=eth0 -drive file=output/images/rootfs.ext4,if=none,format=raw,id=hd0 \
# -device virtio-blk-device,drive=hd0 \

# To use vde backend append:
# -nic vde,mac=12:34:5x:ac:31:13

if [ $? -ne 0 ]; then echo 'Script must be run from within the BR root directory!'; fi
